<#
.SYNOPSIS
    Automatically generates/updates postman-owners.json using the Postman API.

.DESCRIPTION
    Queries the Postman API to retrieve all collections and environments,
    extracts their owner IDs, and creates/updates the postman-owners.json
    configuration file used by Get-PostmanResourceGroups.

.PARAMETER ApiKey
    Postman API key. If not provided, attempts to use the key from existing monitor scripts.

.PARAMETER OutputPath
    Path to save the postman-owners.json file. Defaults to the apiPostman module directory.

.EXAMPLE
    Update-PostmanOwners
    
    Generates postman-owners.json with all collections and environments from your Postman account.

.EXAMPLE
    Update-PostmanOwners -ApiKey "PMAK-xxxxx"
    
    Uses a specific API key to generate the config file.

.NOTES
    File Name      : Update-PostmanOwners.Public.ps1
    Prerequisite   : PowerShell 5.1 or higher, Postman API key
    
    API Endpoints Used:
    - GET https://api.getpostman.com/collections
    - GET https://api.getpostman.com/environments
#>

function Update-PostmanOwners {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [string]$ApiKey,
        
        [Parameter(Mandatory=$false)]
        [string]$OutputPath
    )
    
    # Default API key from environment variable
    if (-not $ApiKey) {
        $ApiKey = $env:POSTMAN_API_KEY
        if (-not $ApiKey) {
            Write-Error "POSTMAN_API_KEY environment variable not set. Run Setup-EnvironmentVariables or provide -ApiKey parameter."
            return
        }
        Write-Host "Using POSTMAN_API_KEY from environment" -ForegroundColor Gray
    }
    
    # Default output path
    if (-not $OutputPath) {
        $OutputPath = Join-Path (Split-Path $PSScriptRoot -Parent) "postman-owners.json"
    }
    
    Write-Host "Fetching data from Postman API..." -ForegroundColor Cyan
    Write-Host ""
    
    $headers = @{"X-Api-Key" = $ApiKey}
    
    # Fetch collections
    Write-Host "Fetching collections..." -ForegroundColor Yellow
    try {
        $collectionsResponse = Invoke-RestMethod -Uri "https://api.getpostman.com/collections" -Headers $headers
        $collections = $collectionsResponse.collections
        Write-Host "  Found $($collections.Count) collections" -ForegroundColor Green
    }
    catch {
        Write-Error "Failed to fetch collections: $_"
        return
    }
    
    # Fetch environments
    Write-Host "Fetching environments..." -ForegroundColor Yellow
    try {
        $environmentsResponse = Invoke-RestMethod -Uri "https://api.getpostman.com/environments" -Headers $headers
        $environments = $environmentsResponse.environments
        Write-Host "  Found $($environments.Count) environments" -ForegroundColor Green
    }
    catch {
        Write-Error "Failed to fetch environments: $_"
        return
    }
    
    Write-Host ""
    Write-Host "Building configuration..." -ForegroundColor Cyan
    
    # Build collections map
    $collectionsMap = @{}
    foreach ($collection in $collections) {
        $collectionsMap[$collection.id] = @{
            name = $collection.name
            owner = $collection.owner.ToString()
        }
    }
    
    # Build environments map
    $environmentsMap = @{}
    foreach ($environment in $environments) {
        $environmentsMap[$environment.id] = @{
            name = $environment.name
            owner = $environment.owner.ToString()
        }
    }
    
    # Create config object
    $config = [PSCustomObject]@{
        collections = $collectionsMap
        environments = $environmentsMap
        notes = @(
            "This file maps Postman collection/environment UUIDs to their owner IDs.",
            "Owner IDs are required by Postman CLI but not stored in report files.",
            "Auto-generated by Update-PostmanOwners on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
            "To refresh this file, run: Update-PostmanOwners"
        )
    }
    
    # Convert to JSON and save
    Write-Host "Saving to: $OutputPath" -ForegroundColor Cyan
    $config | ConvertTo-Json -Depth 10 | Set-Content -Path $OutputPath -Encoding UTF8
    
    Write-Host ""
    Write-Host "✓ Successfully generated postman-owners.json" -ForegroundColor Green
    Write-Host "  Collections: $($collectionsMap.Count)" -ForegroundColor Gray
    Write-Host "  Environments: $($environmentsMap.Count)" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Usage:" -ForegroundColor Cyan
    Write-Host "  Get-PostmanResourceGroups -Path 'report.json' -Format CLI" -ForegroundColor Gray
    Write-Host "  (Will automatically load owner IDs from postman-owners.json)" -ForegroundColor Gray
}

