$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Authorization", "Bearer 8e8c563a68a03bda2c1fce86ffef1261")
$headers.Add("Content-Type", "application/json")

$body = "[
`n    {
`n    `"commodity`": `"FAK`",
`n    `"description`": `"test`",
`n    `"pallets`": 3,
`n    `"palletUnits`": `"PLT`",
`n    `"pieces`": 7,
`n    `"piecesUnits`": `"LD`",
`n    `"weight`": 100,
`n    `"weightUnits`": `"TNL`",
`n    `"cube`": 0.23,
`n    `"cubeUnits`": `"M3`",
`n    `"length`": 2,
`n    `"lengthUnits`": `"FT`",
`n    `"height`": 2,
`n    `"heightUnits`": `"FT`",
`n    `"width`": 2,
`n    `"widthUnits`": `"FT`",
`n    `"items`": 1,
`n    `"unId`": 0,
`n    `"unNumber`": `"string`",
`n    `"temperatureControlled`": `"True`",
`n    `"requestedEquipment`": `"string`",
`n    `"dangerousGoods`": `"False`",
`n    `"area`": 0,
`n    `"areaUnits`": `"FT2`",
`n    `"cost`": 22400,
`n    `"dimWeight`": 100,
`n    `"dimWeightUnits`": `"TNL`",
`n    `"discount`": 201600,
`n    `"discountRate`": 90,
`n    `"distance`": 0,
`n    `"distanceUnits`": `"MI`",
`n    `"field1`": `"`",
`n    `"field2`": `"`",
`n    `"field3`": `"`",
`n    `"field4`": `"`",
`n    `"field5`": `"`",
`n    `"field6`": `"`",
`n    `"field7`": `"`",
`n    `"field8`": `"`",
`n    `"field9`": `"`",
`n    `"field10`": `"`",
`n    `"osdId`": 0,
`n    `"rate`": 2240,
`n    `"rateFromZone`": `"`",
`n    `"ratePer`": 1,
`n    `"rateToZone`": `"CANADA`",
`n    `"rateUnits`": `"TNL`",
`n    `"subCost`": 224000,
`n    `"temperature`": 0,
`n    `"temperatureUnits`": `"C`",
`n    `"time`": 0,
`n    `"timeUnits`": `"HR`",
`n    `"volume`": 0,
`n    `"volumeUnits`": `"GAL`",
`n    `"highValue`": `"False`",
`n    `"regionalRestrictions`": `"False`",
`n    `"manuallyRated`": `"True`",
`n    `"barcodes`": [
`n        {
`n            `"altBarcode1`": `"ab1`",
`n            `"altBarcode2`": `"ab2`",
`n            `"cube`": 10,
`n            `"cubeUnits`": `"FT3`",
`n            `"height`": 10,
`n            `"heightUnits`": `"FT`",
`n            `"length`": 10,
`n            `"lengthUnits`": `"FT`",
`n            `"location`": `"BCVAN`",
`n            `"locationTerminalId`": 0,
`n            `"locationTerminalZone`": `"`",
`n            `"locationTimestamp`": `"2021-06-24T11:14:38.440-07:00`",
`n            `"locationType`": `"Z`",
`n            `"pallets`": 10,
`n            `"palletUnits`": `"PLT`",
`n            `"pieces`": 10,
`n            `"pieceUnits`": `"LD`",
`n            `"temperatureUnits`": `"F`",
`n            `"status`": `"SHIPPER`",
`n            `"statusComment`": `"Test Comment`",
`n            `"volume`": 10,
`n            `"volumeUnits`": `"GAL`",
`n            `"weight`": 1000,
`n            `"weightUnits`": `"LB`",
`n            `"width`": 10,
`n            `"widthUnits`": `"FT`",
`n            `"cubePolicyId`": 0,
`n            `"cubePolicyValue`": 0,
`n            `"handlingNotes`": `"`",
`n            `"intact`": `"True`",
`n            `"isVerified`": `"True`",
`n            `"lifts`": 0,
`n            `"mobileScanned`": `"`",
`n            `"palletGroupId`": `"`",
`n            `"pieceCubing`": `"False`",
`n            `"printStatus`": `"`",
`n            `"tripNumber`": 0,
`n            `"user1`": `"u1`",
`n            `"user2`": `"u2`",
`n            `"user3`": `"u3`",
`n            `"user4`": `"u4`",
`n            `"user5`": `"u5`"
`n        }
`n            ]
`n    }
`n]"

$response = Invoke-RestMethod 'http://localhost:9900/tm/orders/1974/details/' -Method 'POST' -Headers $headers -Body $body
$response | ConvertTo-Json -Depth 5