@(
    @{ Name = 'offset - decimal'; Method = 'GET'; Url = '/'; ExpectedStatus = 200; },
    @{ Name = 'offset - out of bounds'; Method = 'GET'; Url = '/'; ExpectedStatus = 200; },
    @{ Name = 'offset - negative'; Method = 'GET'; Url = '/'; ExpectedStatus = 200; },
    @{ Name = 'offset - string'; Method = 'GET'; Url = '/'; ExpectedStatus = 200; },
    @{ Name = 'limit - decimal'; Method = 'GET'; Url = '/'; ExpectedStatus = 200; },
    @{ Name = 'limit - out of bounds'; Method = 'GET'; Url = '/'; ExpectedStatus = 200; },
    @{ Name = 'limit - negative'; Method = 'GET'; Url = '/'; ExpectedStatus = 200; },
    @{ Name = 'limit - string'; Method = 'GET'; Url = '/'; ExpectedStatus = 200; },
    @{ Name = 'invalidInteger - pathParameter'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'exceedsMaxLength - pathParameter'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'missingRequiredField'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'noValidFields'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'invalidJsonObject'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'invalidJsonArray'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'belowMinValue'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'invalidMaxLength'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'invalidDouble'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'invalidString'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'invalidDateTime'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'invalidInteger'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'invalidEnum'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'InvalidQueryParameter - $select'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'InvalidQueryParameter - $filter'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = 'InvalidQueryParameter - $orderBy'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = '401 Unauthorized'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = '403 Forbidden'; Method = 'GET'; Url = '/'; ExpectedStatus = 200; },
    @{ Name = '404 Not Found'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = '405 Method Not Allowed'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = '200 GET Schema Validation'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; },
    @{ Name = '200 GET Pagination Validation'; Method = 'GET'; Url = 'openapi.json'; ExpectedStatus = 200; }
)
