function New-OrderDetailBarcode {
    <#
    .SYNOPSIS
        Adds an order detail line barcode item
    
    .DESCRIPTION
        POST /orders/{orderId}/details/{orderDetailId}/barcodes
        Adds one or more barcode item records to a specified order and detail line.
        
        Barcode records can be viewed in Customer Service application > Details tab > Barcode Item Details window.
        
        FLEXIBLE TYPE DESIGN:
        - Parameters have minimal type constraints for API testing flexibility
        - Allows testing with intentionally invalid data types
        - API validates and returns proper error codes
    
    .PARAMETER OrderId
        The order ID (required)
    
    .PARAMETER OrderDetailId
        The order detail line ID (required)
    
    .PARAMETER Barcodes
        Array of hashtables, each containing barcode properties. Common properties:
        - barcode (string, max 50) - System-generated scannable barcode
        - altBarcode1 (string, max 50) - Alternate scannable barcode
        - altBarcode2 (string, max 50) - Second alternate scannable barcode
        - cube (number, nullable) - Cubic dimensional value
        - cubeUnits (string, max 3) - Unit of measure for cube
        - height (number, nullable) - Height of handling unit
        - heightUnits (string, max 3) - Unit of measure for height
        - length (number, nullable) - Length of handling unit
        - lengthUnits (string, max 3) - Unit of measure for length
        - width (number, nullable) - Width of handling unit
        - widthUnits (string, max 3) - Unit of measure for width
        - weight (number, nullable) - Weight of handling unit
        - weightUnits (string, max 3) - Unit of measure for weight
        - location (string, max 12) - Last known location identifier
        - pieceCount (integer, nullable) - Number of pieces
        - barcodeSequence (integer, nullable) - Barcode sequence
        
        NOTE: Do not include barcodeId - it is automatically generated by the system.
    
    .PARAMETER BaseUrl
        API base URL. Defaults to $env:TM_API_URL
    
    .PARAMETER Token
        Bearer token. Defaults to $env:TRUCKMATE_API_KEY
    
    .PARAMETER PassThru
        Returns the full API response object instead of unwrapped data
    
    .EXAMPLE
        # Add a single barcode
        New-OrderDetailBarcode -OrderId 12345 -OrderDetailId 1 -Barcodes @(
            @{
                altBarcode1 = "BC123456"
                pieceCount = 10
                weight = 250.5
                weightUnits = "LB"
            }
        )
    
    .EXAMPLE
        # Add multiple barcodes
        $barcodes = @(
            @{ altBarcode1 = "BC001"; pieceCount = 5 },
            @{ altBarcode1 = "BC002"; pieceCount = 3 }
        )
        New-OrderDetailBarcode -OrderId 12345 -OrderDetailId 1 -Barcodes $barcodes
    
    .OUTPUTS
        Created barcode object(s), or JSON error string for testability
    #>
    
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory=$true, Position=0)]
        $OrderId,  # No type constraint - allows testing with invalid types
        
        [Parameter(Mandatory=$true, Position=1)]
        $OrderDetailId,  # No type constraint - allows testing with invalid types
        
        [Parameter(Mandatory=$true, ValueFromPipeline=$true)]
        [array]$Barcodes,
        
        [Parameter(Mandatory=$false)]
        [string]$BaseUrl = $env:DOMAIN,
        
        [Parameter(Mandatory=$false)]
        [string]$Token = $env:TRUCKMATE_API_KEY,
        
        [Parameter(Mandatory=$false)]
        [switch]$PassThru
    )
    
    # Validate token
    if (-not $Token) {
        throw "No authentication token provided. Set TRUCKMATE_API_KEY environment variable or pass -Token parameter."
    }
    
    # Build headers
    $headers = @{
        'Authorization' = "Bearer $Token"
        'Content-Type' = 'application/json'
    }
    
    # Trim base URL
    $BaseUrl = $BaseUrl.TrimEnd('/')
    
    # Build URI
    $uri = "$BaseUrl/orders/$OrderId/details/$OrderDetailId/barcodes"
    
    # Convert body to JSON - API expects a direct array
    $body = $Barcodes | ConvertTo-Json -Depth 10 -AsArray
    
    Write-Verbose "POST $uri"
    Write-Verbose "Body: $body"
    
    # WhatIf support
    if ($PSCmdlet.ShouldProcess("Order $OrderId Detail $OrderDetailId", "Add Barcodes")) {
        # Make API call
        try {
            $response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body
            
            # Return response or unwrapped data
            if ($PassThru) {
                return $response
            }
            else {
                # Unwrap array from response
                if ($response.barcodes) {
                    return $response.barcodes
                } else {
                    return $response
                }
            }
        }
        catch {
            # Output error for interactive use and return JSON string for testability
            if ($_.ErrorDetails.Message) {
                Write-Host "API Returned an error" -ForegroundColor Red
                return $_.ErrorDetails.Message
            }
            else {
                # Fallback for non-API errors (network issues, invalid JSON, etc.)
                Write-Error $_.Exception.Message
                return $null
            }
        }
    }
}
